source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/baijia/specs.git'

platform :ios, '8.0'
# inhibit_all_warnings!

# [!] [Xcodeproj] Generated duplicate UUIDs:
# @see http://stackoverflow.com/a/33440077/456536
# A:
#   export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES
# B:
#   install! 'cocoapods', :deterministic_uuids => false
install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
    installer.pods_project.root_object.attributes["CLASSPREFIX"] = "BJL"
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Baijia Cloud"
end

target 'BJLiveUI' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # dev
    pod 'BJLiveCore', '>= 0.3.0-dylib'
    pod 'BJLiveUI', :path => '../'
    
    # demo
    pod 'Masonry'
    pod 'M9Dev'
    
    # debug
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    
    target 'BJLiveUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'BJLiveUIUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
